apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: citylarry/front:latest
        ports:
        - containerPort: 80
        env:
        - name: ALPHA_URI
          valueFrom:
            configMapKeyRef:
              name: service-urls
              key: ALPHA_URI
              optional: true
        - name: BETA_URI
          valueFrom:
            configMapKeyRef:
              name: service-urls
              key: BETA_URI
              optional: true
        - name: GAMA_URI
          valueFrom:
            configMapKeyRef:
              name: service-urls
              key: GAMA_URI
              optional: true

---
apiVersion: v1
kind: Service
metadata:
  name: front-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: front